version: '3.9'

services:
  productivitykeeperweb:
    build:
      context: ./ProductivityKeeperWeb
      dockerfile: Dockerfile
    restart: always
    ports:
      - '65070:80'
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORTS": 443
      ASPNETCORE_HTTP_PORTS": 80
      ASPNETCORE_Kestrel__Certificates__Default__Password: kitce
      ASPNETCORE_Kestrel__Certificates__Default__Path: ./ProductivityKeeperWeb/aspnetapp.pfx
    command: ["dotnet", "ProductivityKeeperWeb.dll"]
    volumes:
      - ./ProductivityKeeperWeb:/app/ProductivityKeeperWeb

  productivitykeeperclient:
    build:
      context: ./ProductivityKeeperClient
      dockerfile: Dockerfile  # Assuming the Dockerfile is in the frontend project directory
    ports:
      - '4201:4201'
    environment:
      NODE_ENV: "production"
    volumes:
      - ./ProductivityKeeperClient:/app/ProductivityKeeperClient 

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
      - ./ssl:/etc/nginx/ssl
      -  ./sites-enabled/:/etc/nginx/sites-enabled
      -  ./logs/:/var/logs/nginx/myapp.local/
    ports:
        - '44398:443'
    depends_on:
      - productivitykeeperweb