
// This file was auto-generated by ML.NET Model Builder. 

using UserTasksProgressPredictionEngine;

internal class Program
{
    private static void Main(string[] args)
    {
        string connectionString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=prodKeepDb;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
        var pe = new StatisticPredictionEngine();

        var predications = pe.Predict(connectionString, 16, 7);

        Console.WriteLine("Count of done Forecast");
        Console.WriteLine("---------------------");
        foreach (var predication in predications)
        {
            Console.WriteLine($"{predication.Date}  -  {predication.CountOfDone} ({predication.Actial})");
        }
    }
}
