name: Build and deploy ASP.Net Core app to Azure Web App - ProductivityKeeper

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEB_APP_NAME: "ProductivityKeeper"
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore ProductivityKeeperWeb/ProductivityKeeperWeb.csproj
        
      - name: Build with dotnet
        run: dotnet build ProductivityKeeperWeb/ProductivityKeeperWeb.csproj --no-restore --configuration Release

      - name: dotnet publish
        run: dotnet publish ProductivityKeeperWeb/ProductivityKeeperWeb.csproj -c Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.AZURE_WEB_APP_NAME }}
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
     
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.AZURE_WEB_APP_NAME }}
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7407BC39DCFE4E19929D0808534E4658 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F7E9C2F43FAB4BA48730B7A7BC81FEEC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_732CB91B1949473FAB70B15EF9F68BBA }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEB_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
      - name: Display deployment logs
        run: Get-Content -Path "D:\home\LogFiles\kudu\trace\DeploymentLog.txt"
